### ISSUE TITLE
Support for latest version of localstack

### ISSUE THREAD

**Issue by kritulrathod** [commandeer/open#79]
Is there a way to use the latest versions of the localstack (localstack/localstack-full:latest) image with commandeer.

I already have the docker image running however, when I start the commandeer localstack services, It launches (localstack/localstack:0.11.2)

Is there a way to configure to use the latest version.

![image](https://user-images.githubusercontent.com/7039094/94776373-424f0f80-03df-11eb-8bfd-569df99c21b1.png)

**Comment by fsproru** [comment]
Hi @kritulrathod, good call, we should add the ability for you to specify the LocalStack image you already have. We'll look into it in the future releases.

**Comment by ssanri** [comment]
with latest localstack, all ports are removed and served under 4566. now in commandeer I see except elasticsearch ( which was 4566) all services are offline. if I try to start them, then it creates another container and stops my current one. Also another bottleneck is, I can't modify environment variables of the container created by commandeer. If we can at least have an option to edit port numbers for services I think that would be quick solution.

**Comment by fsproru** [comment]
Hi @ssanri, to modify the ports on the LocalStack container, you can add some environment variables in LocalStack settings. We pass them to the container once it restarts.

On a related note, you can also configure the ports Commandeer uses in the AWS section of your Commandeer account.

**Comment by ssanri** [comment]
Correct, I can change the ports localstack uses, but still using the old image which has some bugs around api gateway. That’s the main reason I was using latest localstack image. Changing ports on old localstack image doesn’t really help in that case. I am not sure what did you mean by changing the ports commandeer uses in the AWS section. I don’t/can’t see any settings to define these ports.  (1). Also I have latest localstack container running in docker but commandeer shows only 1 service is running.    Serdar SanriSr Engineer, Fern Health(e) serdar@fernhealth.comwww.fernhealth.com  From: Alex TamoykinSent: Tuesday, October 27, 2020 12:17 PMTo: commandeer/openCc: ssanri; MentionSubject: Re: [commandeer/open] Support for latest version of localstack (#79) Hi @ssanri, to modify the ports on the LocalStack container, you can add some environment variables in LocalStack settings. We pass them to the container once it restarts.On a related note, you can also configure the ports Commandeer uses in the AWS section of your Commandeer account.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ssanri** [comment]
Ok, I think I got it. I found the port settings.  Thank you  Serdar SanriSr Engineer, Fern Health(e) serdar@fernhealth.comwww.fernhealth.com  From: Alex TamoykinSent: Tuesday, October 27, 2020 12:17 PMTo: commandeer/openCc: ssanri; MentionSubject: Re: [commandeer/open] Support for latest version of localstack (#79) Hi @ssanri, to modify the ports on the LocalStack container, you can add some environment variables in LocalStack settings. We pass them to the container once it restarts.On a related note, you can also configure the ports Commandeer uses in the AWS section of your Commandeer account.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by fsproru** [comment]
Some great news, we're working on the patch release which will allow to set
the version of LocalStack Docker image to run. We'll deploy it soon.

**Comment by fsproru** [comment]
@kritulrathod @ssanri we just pushed 1.4.1 out. If you open the app, it should auto-update to the latest version. We added an option to LocalStack settings allowing you to specify a version of LocalStack to run. You can simplify put `localstack/localstack:latest` there and restart LocalStack.

<img width="682" alt="localstack-custom-image" src="https://user-images.githubusercontent.com/1017606/97518823-44ac7700-1955-11eb-8ff8-7316f9cb7aaf.png">

If you have different versions of LocalStack containers running, you can stop those from the Docker Container page.

Let us know if you run into any issues and thanks for your feedback.

**Comment by ssanri** [comment]
This is very helpful and thank you for quick escalation. This should help a lot. 

Since Commandeer can access other docker containers, would that be possible in this screen to give user an option to select existing containers created with localstack namespace, or create new one? I can see the use of it. If someone has a container (like me already set ) and has bunch of data already recorded to keep persistent after restarts, that will allow user to select existing container and start, and commandeer picks up from there. 

also addition to work being done, latest localstack fully dropped custom ports and only serves services on 4566 edge port. Is there any change on LocalStack section on commandeer to edit ports? I did what you suggested earlier and replaced all the ports in AWS account settings, that indeed worked for individual sections to work properly ( DynamoDB etc ) but in localstack section all the services still shows as offline hence still looking for deprecated old ports for each service.

**Comment by kritulrathod** [comment]
@fsproru Thanks for quickly churning out this feature. Agree with @ssanri , I too had issues working with single port version. Will try the updated version and see if I still get that error. 

Thanks again...

**Comment by fsproru** [comment]
@ssanri, I see what you're saying. Great feedback!

Regarding the Docker container version, what Commandeer does currently is
it finds a container with a matching image name from your settings or
`localstack/localstack:0.11.2` by default. I like your idea though. And
you're exactly right, if there are multiple LocalStack containers with the
same image name, it'll just pick up the first one. What we can do is do so
by default if there is only one container with a matching image. And like
you said, prompt the user with a choice of existing containers to connect
to that container and manage it from Commandeer. We can also allow changing
the container you're connected to. Love it!

Now, for LocalStack settings:
All endpoints are set to `http://localhost:4566` in my AWS section for my
local account. Which makes it work with the latest version of LocalStack.

That said, you bring up a good point, the LocalStack page still mentions
ports, so as the individual service page. We can show the service URLs here.

Another thing we can do is to move the AWS endpoint section inside
LocalStack settings which will make it easier to have all settings in the
same place.

We’ll look into making these changes in the future releases. Great
feedback. If you have any more feedback, please don’t hesitate to reach out.

**Comment by fsproru** [comment]
the version 1.5.1 has the ability to specify a custom version of localstack container, closing this issue.
